admin_portal/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'admin_portal'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(views.HomePageView.as_view()), name='home'),
    path('covid-questionnaire/', views.CovidQuestionnairePage.as_view(),
         name='covid-questionnaire'),
    path('leave-application/', views.LeaveApplicationPage.as_view(),
         name='leave-application'),
    path('banking-detail/', views.BankingDetailPageView.as_view(),
         name='banking-detail'),
    path('pending-leave-applications/',
         views.PendingLeaveApplicationPage.as_view(), name='pending-leaves'),
    path('chat/', views.ChatPageView.as_view(), name='chat'),
    # path('checkin/', views.CheckinPageView.as_view(), name='check_in'),
    # path('checkinoffsite/', CheckinOffsitePageView.as_view(), name='checkinoffsite'),
    path('accountprofile/', views.AccountProfilePageView.as_view(),
         name='accountprofile'),
    path('printusers/', views.PrintUsersPageView.as_view(), name='printusers'),
    path('printcovid/', views.PrintCovidPageView.as_view(), name='printcovid'),
    path('covidfor/', views.CovidForPageView.as_view(), name='covidfor'),
    path('calendar/', views.CalendarPageView.as_view(), name='calendar'),
    path('checkoutlc/', views.CheckOutlcPageView.as_view(), name='checkoutlc'),
    path('checkoutoff/', views.CheckOutoffPageView.as_view(), name='checkoutoff'),
]

lcstudio_adminportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_portal.urls')),
    path('users/', include("users.urls", namespace="users")),
    # path('auth/', include('authentication.urls')),
    # path('', CheckinPageView.as_view(), name='home')
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

handler404 = 'admin_portal.views.error_404'
handler500 = 'admin_portal.views.error_500'
handler403 = 'admin_portal.views.error_403'
handler400 = 'admin_portal.views.error_400'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Register, RegisterParttwo, PendingAccounts, ActivatePendingAccount, activate_account, ViewProfile, \
    AdminPageView, RegistrationConfirmation, update_profile, update_bankingdetails, update_kin_details, \
    update_contact_details


app_name = 'users'

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('register/step-2/', RegisterParttwo.as_view(), name='register2'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('pending-accounts/', PendingAccounts.as_view(), name='pending-accounts'),
    path('pending-accounts/<int:pk>', ActivatePendingAccount.as_view(),
         name='activate-pending-accounts'),
    path('activate-account/<int:pk>', activate_account, name='activate-account'),
    path('view-profile/', ViewProfile.as_view(), name='view-profile'),
    path('admin-page/', AdminPageView.as_view(), name='admin'),
    # path('account-profile/', AccountProfilePageView.as_view(), name='accountprofile'),
    path('registration-confirmation/', RegistrationConfirmation.as_view(),
         name='registration-confirmation'),
    path('update-profile/<int:pk>/', update_profile, name='update-profile'),
    path('update-banking-details/', update_bankingdetails,
         name='update-banking-details'),
    path('update-kin-details/', update_kin_details, name='update-kin'),
    path('update-contact-details/', update_contact_details, name='update-contact')
]

templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container accpro">
	<div class="row border-bottom pb-3">
		<div class="col-6 d-sm-none d-md-block d-none d-sm-block">
			<div class="row">
				<img class="profilepic col-md-6 rounded-circle" src="{{ user.imageURL }}" alt="profilepic" />
			</div>
		</div>
		<div class="col-md-6">
            <div class="personal-details">
                <ul class="nav nav-tabs">
                	<li class="nav-item">
                  		<a class="nav-link active" aria-current="page" href="{% url 'users:viewprofile'%}">Overview</a>
                	</li>
                	<li class="nav-item">
                  		<a class="nav-link" href="{% url 'users:update-profile' pk=user.id %}">Update</a>
                	</li>
              	</ul>
            	<div class="personal-details--holder">
                	<div class="flex  py-2">
                  		<span class="text-gray-500">First Name</span>
                  		<span class="ml-auto text-gray-900">{{user.first_name}}</span>
                	</div>
                	<div class="flex border-t border-gray-200 py-2">
                  		<span class="text-gray-500">Last Name</span>
                  		<span class="ml-auto text-gray-900">{{user.last_name}}</span>
                	</div>
                	<div class="flex border-t border-gray-200 py-2">
                  		<span class="text-gray-500">Email</span>
                  		<span class="ml-auto text-gray-900">{{user.email}}</span>
                	</div>
                	<div class="flex border-t border-gray-200 py-2">
                  		<span class="text-gray-500">Phone Number</span>
                  		<span class="ml-auto text-gray-900">{{user.cell_number}}</span>
                	</div>
                	<div class="flex border-t border-b mb-6 border-gray-200 py-2">
                  		<span class="text-gray-500">Status</span>
                  		<span class="ml-auto text-yellow-500 hover:text-blue-500">
                    	{{user.groups.all.0}}
                  		</span>
                	</div>
              	</div>
            </div>
		</div>
	</div>
	<div class="row border-bottom pb-3 ">
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="{% url 'users:update-banking-details' %}">Banking Details</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:update-contact' %}">Contact Details</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:update-kin' %}">Next of Kin</a>
			</li>
			<li class="nav-item">
				<a class="nav-link " href="#" >Disabled</a>
			</li>
		</ul>
	</div>
				
		
</div>
{% endblock content %}

templates/profile/profile_base.html
{% include 'base.html' %}
{% load static %}
{% block content %}
<div class="container accpro mb-4">
			<div>

				<div class="row border-bottom pb-3">
					<div class="col-6 d-sm-none d-md-block d-none d-sm-block">
						<div class="row">
							<img
								class="profilepic col-md-6 rounded-circle"

                                src="{{ user.imageURL }}"
								alt="profilepic"
							/>
						</div>
					</div>
					<div class="col-md-6">
            <div class="personal-details">
              <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'users:view-profile'%}">Overview</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'users:update-profile' pk=user.id %}">Update</a>
                  </li>
              </ul>
              <div class="personal-details--holder">
                <div class="flex  py-2">
                    <span class="text-gray-500">First Name: </span>
                    <span class="ml-auto text-gray-900">{{user.first_name}}</span>
                  </div>
                  <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Last Name: </span>
                    <span class="ml-auto text-gray-900">{{user.last_name}}</span>
                  </div>
                  <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email: </span>
                    <span class="ml-auto text-gray-900">{{user.email}}</span>
                  </div>
                  <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Phone Number: </span>
                    <span class="ml-auto text-gray-900">{{user.cell_number}}</span>
                  </div>
                  <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Status: </span>
                    <span class="ml-auto text-yellow-500 hover:text-blue-500">
                      {{user.groups.all.0}}
                    </span>
                  </div>
              </div>
            </div>
		</div>
	</div>
      
    </div>
</div>
{% endblock content %}

templates/profile/updatebankingdetails.html
{% include 'profile/profile_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<div class="container accpro">
   <div class="row border-bottom pb-3 ">
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link " href="{% url 'admin_portal:covid-questionnaire' %}">Covid Questionaire</a>
			</li>
         <li class="nav-item">
				<a class="nav-link" href="{% url 'users:update-contact' %}">Contact Details</a>
			</li>
         {% if request.user.roles != 'visitor' %}
			<li class="nav-item">
				<a class="nav-link active " aria-current="page" href="{% url 'users:update-banking-details' %}">Banking Details</a>
			</li>
			
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:update-kin' %}">Next of Kin</a>
			</li>
			{% endif %}
		</ul>
	</div>
    <div class="personal-details--holder">
            <form  method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{form|crispy}}
               <button class="btn btn-primary" type="submit">Submit</button>
            </form>
         </div>
</div>

templates/profile/updatecontactdetails.html
{% include 'profile/profile_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<div class="container accpro">
   <div class="row border-bottom pb-3 ">
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link " href="{% url 'admin_portal:covid-questionnaire' %}">Covid Questionaire</a>
			</li>
         <li class="nav-item">
				<a class="nav-link active" href="{% url 'users:update-contact' %}">Contact Details</a>
			</li>
			
         {% if request.user.roles != 'visitor' %}
			<li class="nav-item">
				<a class="nav-link  " aria-current="page" href="{% url 'users:update-banking-details' %}">Banking Details</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:update-kin' %}">Next of Kin</a>
			</li>
			{% endif %}
		</ul>
	</div>
   <div class="personal-details--holder">
            <form  method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{form|crispy}}
               <button class="btn btn-primary" type="submit">Submit</button>
            </form>
   </div>
</div>

templates/profile/updatenextofkin.html
{% include 'profile/profile_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<div class="container accpro mb-4">
   <div class="row border-bottom pb-3 ">
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link " href="{% url 'admin_portal:covid-questionnaire' %}">Covid Questionaire</a>
			</li>
			<li class="nav-item">
				<a class="nav-link " href="{% url 'users:update-contact' %}">Contact Details</a>
			</li>
         {% if request.user.roles != 'visitor' %}
         <li class="nav-item">
				<a class="nav-link  " aria-current="page" href="{% url 'users:update-banking-details' %}">Banking Details</a>
			</li>
			
			<li class="nav-item">
				<a class="nav-link active" href="{% url 'users:update-kin' %}">Next of Kin</a>
			</li>
			{% endif %}
		</ul>
	</div>
    <div class="personal-details--holder">

            <form  method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{ form|crispy }}
               <button class="btn btn-primary" type="submit">Submit</button>
            </form>
         </div>
</div>

templates/profile/updateprofile.html
{% include 'profile/profile_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<div class="container accpro mt-2 mb-5">
    <div class="personal-details--holder">
            <form  method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{form|crispy}}
               <button class="btn btn-primary" type="submit">Submit</button>
            </form>
         </div>
</div>