admin_portal/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'admin_portal'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(views.HomePageView.as_view()), name='home'),
    path('covid-questionnaire/', views.CovidQuestionnairePage.as_view(),
         name='covid-questionnaire'),
    path('leave-application/', views.LeaveApplicationPage.as_view(),
         name='leave-application'),
    path('banking-detail/', views.BankingDetailPageView.as_view(),
         name='banking-detail'),
    path('pending-leave-applications/',
         views.PendingLeaveApplicationPage.as_view(), name='pending-leaves'),
    path('chat/', views.ChatPageView.as_view(), name='chat'),
    # path('checkin/', views.CheckinPageView.as_view(), name='check_in'),
    # path('checkinoffsite/', CheckinOffsitePageView.as_view(), name='checkinoffsite'),
    path('accountprofile/', views.AccountProfilePageView.as_view(),
         name='accountprofile'),
    path('printusers/', views.PrintUsersPageView.as_view(), name='printusers'),
    path('printcovid/', views.PrintCovidPageView.as_view(), name='printcovid'),
    path('covidfor/', views.CovidForPageView.as_view(), name='covidfor'),
    path('calendar/', views.CalendarPageView.as_view(), name='calendar'),
    path('checkoutlc/', views.CheckOutlcPageView.as_view(), name='checkoutlc'),
    path('checkoutoff/', views.CheckOutoffPageView.as_view(), name='checkoutoff'),
]

lcstudio_adminportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_portal.urls')),
    path('users/', include("users.urls", namespace="users")),
    # path('auth/', include('authentication.urls')),
    # path('', CheckinPageView.as_view(), name='home')
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

handler404 = 'admin_portal.views.error_404'
handler500 = 'admin_portal.views.error_500'
handler403 = 'admin_portal.views.error_403'
handler400 = 'admin_portal.views.error_400'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Register, RegisterParttwo, PendingAccounts, ActivatePendingAccount, activate_account, ViewProfile, \
    AdminPageView, RegistrationConfirmation, update_profile, update_bankingdetails, update_kin_details, \
    update_contact_details


app_name = 'users'

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('register/step-2/', RegisterParttwo.as_view(), name='register2'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('pending-accounts/', PendingAccounts.as_view(), name='pending-accounts'),
    path('pending-accounts/<int:pk>', ActivatePendingAccount.as_view(),
         name='activate-pending-accounts'),
    path('activate-account/<int:pk>', activate_account, name='activate-account'),
    path('view-profile/', ViewProfile.as_view(), name='view-profile'),
    path('admin-page/', AdminPageView.as_view(), name='admin'),
    # path('account-profile/', AccountProfilePageView.as_view(), name='accountprofile'),
    path('registration-confirmation/', RegistrationConfirmation.as_view(),
         name='registration-confirmation'),
    path('update-profile/<int:pk>/', update_profile, name='update-profile'),
    path('update-banking-details/', update_bankingdetails,
         name='update-banking-details'),
    path('update-kin-details/', update_kin_details, name='update-kin'),
    path('update-contact-details/', update_contact_details, name='update-contact')
]

admin_portal/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as _
from PIL import Image
from datetime import datetime


# Custom Account manager
class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, password, **other_fields):

        # Default fields
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        other_fields.setdefault('first_name', 'First Name')
        other_fields.setdefault('last_name', 'Last Name')

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True')

        if other_fields.get('is_active') is not True:
            raise ValueError('Superuser must be assigned to is_active=True')

        return self.create_user(email, password, **other_fields)

    def create_user(self, email, password, **other_fields):
        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        other_fields.setdefault('user_name', 'Username')
        other_fields.setdefault('first_name', 'First Name')
        other_fields.setdefault('last_name', 'Last Name')
        user = self.model(email=email, password=password)
        user.set_password(password)
        user.save()
        return user


# custom user with email as username
# changing newuser to user
class User(AbstractBaseUser, PermissionsMixin):
    role = (
        ("staff", "STAFF"),
        ("business_unit", "BUSINESS UNIT"),
        ("student", "STUDENT"),
        ("visitor", "VISITOR"),
    )
    gender_choices = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    marital_choices = (
        ("single", "Single"),
        ("married", "Married"),
        ("widowed", "Widowed"),
        ("divorced", "Divorced"),
    )

    # signup fields
    image = models.ImageField(
        null=True, blank=True, default="profile_pictures/default.jpg", upload_to='profile_pictures/')
    email = models.EmailField(_('email address'), unique=True)
    user_name = models.CharField(max_length=150, blank=True, null=True)
    # Employee identification
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)

    # Personal details
    gender = models.CharField(choices=gender_choices, max_length=6)
    date_of_birth = models.DateField(
        "Date of birth(mm/dd/yyyy) ", auto_now_add=False, auto_now=False, blank=True, null=True)
    marital_status = models.CharField(choices=marital_choices, max_length=20)
    nationality = models.CharField(max_length=50)
    identity_number = models.CharField(max_length=20, null=True, blank=True)

    # Contact info
    address = models.TextField(max_length=200)
    telephone_number = models.CharField(max_length=15, null=False, blank=False)
    cell_number = models.CharField(max_length=15, null=False, blank=False)

    # Permanent address
    permanent_address = models.TextField(max_length=200, null=True, blank=True)
    permanent_telephone_number = models.CharField(
        max_length=15, null=False, blank=False)

    # authentication
    roles = models.CharField(max_length=15, choices=role, default="visitor")
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    # group = models.CharField(max_length=150, null=False, blank=False)

    # Next of Kin
    next_of_kin_name = models.CharField(max_length=50)
    next_of_kin_relationship = models.CharField(max_length=50)
    next_of_kin_contact_number = models.CharField(max_length=15)

    date_joined = models.DateTimeField(
        verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(
        verbose_name="last login", auto_now=True, null=True)

    objects = CustomAccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name']

    def __str__(self):
        return f' {self.email}'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    # image re-sizing using PIL
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)


class LifeChoicesMember(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    ID_number = models.BigIntegerField(null=True, blank=False)
    chronic_condition = models.CharField(max_length=50, null=True, blank=False)
    allergies = models.CharField(max_length=50, null=True, blank=False)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


# life-choice members
class LifeChoicesAcademy(models.Model):
    user = models.ForeignKey(LifeChoicesMember, on_delete=models.CASCADE)
    student_number = models.CharField(max_length=13, null=True, blank=False)

    def __str__(self):
        return self.user.user.user_name


# life choices stuff
class BankingDetail(models.Model):
    user = models.ForeignKey(LifeChoicesMember, on_delete=models.CASCADE)
    # Banking details
    bank_name = models.CharField(max_length=50, null=True, blank=False)
    account_holder_name = models.CharField(
        max_length=50, null=True, blank=False)
    account_number = models.CharField(max_length=50, null=True, blank=False)
    branch_name = models.CharField(max_length=50, null=True, blank=False)
    branch_number = models.CharField(max_length=50, null=True, blank=False)
    # tax number
    tax_number = models.CharField(max_length=25, null=True, blank=False)

    def __str__(self):
        return f'{self.user.user.first_name} {self.user.user.last_name}'


# Covid Questionnaires
class CovidQuestionnaire(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # info
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    Shortness_of_breath = models.BooleanField(default=True)
    sore_throat = models.BooleanField(default=True)
    loss_of_taste_or_smell = models.BooleanField(default=True)
    contact_with_Covid = models.BooleanField(default=True)
    nasal_congestion = models.BooleanField(default=True)
    diarrhea = models.BooleanField(default=True)
    nausea = models.BooleanField(default=True)
    time_in = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Covid questionnaire taken by {self.user} on {self.time_in}"


# Leave Application
class LeaveApplication(models.Model):
    """
    leave application can only be done by lifechoices stuff and not general and lifechoices members
    """
    CATEGORY = (
        ('Annual Leave', 'Annual Leave'),
        ('Sick Leave', 'Sick Leave'),
        ('Family Leave', 'Family Leave'),
        ('Unpaid Leave', 'Unpaid Leave'),
        ('Study Leave', 'Study Leave'),
        ('Compensation Leave', 'Compensation Leave'),
        ('Other Leave', 'Other Leave')
    )
    user = models.ForeignKey(LifeChoicesMember, on_delete=models.CASCADE)

    # info
    category = models.CharField(
        max_length=45, null=False, blank=False, choices=CATEGORY)
    pre_authorisation = models.BooleanField(
        default=False, blank=False, null=False)
    personal_message = models.CharField(max_length=200, null=True, blank=True)
    leave_date_from = models.DateField(blank=False, null=False)
    leave_date_to = models.DateField(blank=False, null=False)

    # def __str__(self):
    #     return f"Leave request by {self.user} from {self.leave_date_from} - {self.leave_date_to}"


class CheckIn(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    remote_work = models.BooleanField(default=False)
    location = models.CharField(max_length=255, blank=True)
    time_signed_in = models.DateTimeField(auto_now_add=True)
    time_signed_out = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"{self.user} signed in at {self.location} at the time of {self.time_signed_in}"

templates/account.html
{% extends 'base.html' %}
{% block content %}
    <div class="container  px-5 accountcolor">
		<span><a href="{% url 'users:pending-accounts' %}" style="text-decorations:none; color:inherit;"><i class="fas fa-arrow-left"></i></a></span>
        <div class='row'>
            <div class="col-12">
                <h1 class=" accpend">Account Pending</h1>
            </div>
        
            <div class="col-12">
                <h2 class='py-3 accreq'>{{ user.first_name }} {{ user.last_name }} has
                        requested to create an
                        Account.
                </h2>
            </div>
        
            <div class="col-12">
                <span class=''>Please verify the information entered is
                    correct before approving the account.</span>
            </div>        
        </div>
        <div class="row">
				<div class="container">
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Username</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.user_name }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Email</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.email }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> FirstName</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.first_name }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> LastName</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.last_name }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Gender</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.gender }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Date of Birth</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.date_of_birth }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Marital Status</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.marital_status }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Nationality</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.nationality }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Address</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.address }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Telephone Number</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.telephone_number }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Roles</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.roles }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Next of Kin Name</span>
						</div>
						<div class="col-6">
							<span class="account-info"> {{ user.next_of_kin_name }}</span>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Next of Kin Relationship</span>
						</div>
						<div class="col-6">
							<span class="account-info">
								{{ user.next_of_kin_relationship }}</span
							>
						</div>
					</div>
					<div class="row pt-3">
						<div class="col-6">
							<span class="account-label"> Next of Kin Contact Number</span>
						</div>
						<div class="col-6">
							<span class="account-info">
								{{ user.next_of_kin_contact_number }}</span
							>
						</div>
					</div>
				</div>
			</div>
            <div class="row py-3">
                <div class="col-6">
                    <a type="button"class='btn btn-dark form-control declinebtn' href="{% url 'users:pending-accounts' %}">Decline</a>
                </div>
                <div class="col-6">
                    <a type="button" class='btn btn-success form-control approvebtn' href="{% url 'users:activate-account' user.id %}">Approve</a>
                </div>                           
            </div>
    </div>
    

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Life Choices Admin</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,500|Open+Sans">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&family=Epilogue:wght@200;300&display=swap" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

   <script>
           $('[data-toggle="collapse"]').on('click',function(e){
    if ( $(this).parents('.accordion').find('.collapse.show') ){
        var idx = $(this).index('[data-toggle="collapse"]');
        if (idx == $('.collapse.show').index('.collapse')) {
            // prevent collapse
            e.stopPropagation();
        }
    }
});

        </script>






<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'admin_portal:home' %}">
        <span class="sr-only">(current)</span>
        <img id="Logo" src="{% static 'admin_portal/Img/logo.png' %}"/>
      </a>
      <div class="btn-group">
        {% if not user.is_authenticated %}
        <a href="{% url 'users:login' %}" id="SignInButton">Sign In</a>
        {% else %}
        <button id="UserDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-bars fa-2x" style="color: white"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          {% if user.roles != 'visitor' %}
          <button class="dropdown-item d-none" type="button">Messages</button>
<!--          <button class="dropdown-item" type="button">Clock In/Out</button>-->
          <button class="dropdown-item" type="button"><a class="navdrop" href="{% url 'admin_portal:leave-application' %}">Leave Days</a></button>
          {% endif %}
          <a href="{% url 'users:view-profile' %}" class="dropdown-item" type="button">Profile</a>
            <a href="{% url 'users:logout' %}" class="dropdown-item" type="button">Log Out</a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>
    <div class="container pt-5 mt-5 ">
      {% if messages %}
          <ul class="messages">
              {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
              {% if message.tags %}
                <li  class="{{ message.tags }}">{{ message }}</li>
                {% endif %}
            </div>
              {% endfor %}
          </ul>
      {% endif %}
      {% block content %}
      {% endblock content %}
    </div>
<script>
    var btn = document.getElementsByClassName("checkinbtn");
    var x = document.getElementById("latitude");
    var y = document.getElementById("longitude");
			function getLocation() {
			if (navigator.geolocation) {
				navigator.geolocation.getCurrentPosition(showPosition);
			} else {
				x.value = "Geolocation is not supported by this browser.";
			}
			}

			function showPosition(position) {
            console.log(position)
			x.value = position.coords.latitude;
			y.value = position.coords.longitude;
			for (i = 0; i < btn.length; i++) {
			    btn[i].style.display = "block";
            };

			}
			getLocation()

</script>
</body>
</html>

templates/covidfor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
			<input
				type="hidden"
				name="csrfmiddlewaretoken"
				value="IO7Lo72j2x2dR4Qr0Nrso1x5TuG3w0386cjIDD7PIQUNCHgr1ECGukDImkF3E6zk"
			/>
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Covid-19 Questionnairetest</legend>
				<div class="form-group">
					<div id="div_id_temperature" class="form-group">
						<label for="id_temperature" class="requiredField">
							Temperature<span class="asteriskField">*</span>
						</label>
						<div class="">
							<input
								type="number"
								name="temperature"
								step="0.01"
								class="numberinput form-control"
								required=""
								id="id_temperature"
							/>
						</div>
					</div>
					</div>


					<div class="form-group col-md-4">

						<div id="div_id_Shortness_of_breath" class="form-check ">
							<div class="row">
							<label for="id_Shortness_of_breath" class="form-check-label col-md">
								Shortness of breath
							</label>

							<label class="switch col-md-2">
								<input name="Shortness_of_breath" id="id_Shortness_of_breath" type="checkbox">
								<span class="slider round">yes</span>
							</label>
							</div>
						</div>
					</div>
						<div class="form-group col-md-4">
						<div id="div_id_sore_throat" class="form-check">
							<div class="row">
							<label for="id_sore_throat" class="form-check-label col-md">
								Sore throat
							</label>

									<label class="switch col-md-2">
									  <input name="sore_throat" id="id_sore_throat" type="checkbox">
									  <span class="slider round">yes</span>
									</label>
							</div>
						</div>
					</div>
							<div class="form-group col-md-4">
						<div id="div_id_loss_of_taste_or_smell" class="form-check">
							<div class="row">
							<label for="id_loss_of_taste_or_smell" class="form-check-label col-md">
								Loss of taste or smell
							</label>

									<label class="switch col-md-2">
									  <input name="loss_of_taste_or_smell" id="id_loss_of_taste_or_smell" type="checkbox">
									  <span class="slider round">yes</span>
									</label>
							</div>
						</div>
					</div>
							<div class="form-group col-md-4">
						<div id="div_id_contact_with_Covid" class="form-check">
							<div class="row">
							<label for="id_contact_with_Covid" class="form-check-label col-md">
								Contact with Covid
							</label>

									<label class="switch col-md-2">
									  <input name="contact_with_Covid" id="id_contact_with_Covid" type="checkbox">
									  <span class="slider round">yes</span>
									</label>
							</div>
						</div>
					</div>




					<div class="form-group col-md-4">
						<div id="div_id_nasal_congestion" class="form-check">
							<div class="row">
							<label for="id_nasal_congestion" class="form-check-label col-md">
								Nasal congestion
							</label>

									<label class="switch col-md-2">
									  <input name="nasal_congestion" id="id_nasal_congestion" type="checkbox">
									  <span class="slider round">yes</span>
									</label>


							</div>
						</div>
					</div>
					<div class="form-group col-md-4">
						<div id="div_id_diarrhea" class="form-check">
							<div class="row">
							<label for="id_diarrhea" class="form-check-label col-md">
								Diarrhea
							</label>


									<label class="switch col-md-2">
									  <input name="diarrhea" id="id_diarrhea" type="checkbox">
									  <span class="slider round">yes</span>
									</label>


							</div>
						</div>
					</div>
					<div class="form-group col-md-4">
						<div id="div_id_nausea" class="form-check">
							<div class="row">
							<label for="id_nausea" class="form-check-label col-md" > Nausea </label>


									<label class="switch col-md-2">
									  <input name="nausea" id="id_nausea" type="checkbox">
									  <span class="slider round">yes</span>
									</label>

							</div>
						</div>
					</div>


			</fieldset>
			<button class="btn btn-primary covidqbtn" type="submit">Submit</button>
		</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="container-fluid">
        <div class="row">
            <h4 class="col-12 "><i class="fas fa-map-marker-alt"><span class="accpend">LIFE CHOICES</span></i></h4>
        </div>
       <h1>Hey, {{ user.user_name }}</h1>
    <div id="NotificationBox">
        {% if user.is_active  %}
            {% if pending_accounts.count > 0 %}
                <a href="{% url 'users:pending-accounts' %}"><div class="notification-item col-12">{{ pending_accounts.count }} Pending accounts</div></a>
            {% endif %}
            {% if leaves_applications.count > 0 %}
                <a href="{% url 'admin_portal:pending-leaves' %}"><div class="notification-item col-12">{{ leaves_applications.count }} Pending Leaves</div></a>
            {% endif %}
        {% endif %}
        <!--
            <div class="notification-item">You have 7 new messages</div>
        -->
        <div class="row mb-3">
            <div class="col-md-4">
                <a href="{% url 'admin_portal:covid-questionnaire' %}" class="notification-item">Covid Questionnaire</a>
            </div>
            <div class="col-md-4">
                <a href="#" class="notification-item">Notifications</a>
            </div>
            <div class="col-md-4">
                <a href="#" class="notification-item">Messages</a>
            </div>

        </div>
        
    </div>
        <!-- here-->
    <div id="NavigationBox" class="row gutter">
        <div class=" col-6 col-md-4 col-lg-4">
<!--            <a href="#">-->
            <div class="icon-card card">
                <img src="{% static 'admin_portal/Img/briefcase.png' %}"/>
                <h2>Check Into Life Choices</h2>
            </div>
<!--            </a>-->
        </div>

        <div class=" col-6 col-md-4 col-lg-4">
            <a href="/checkinoffsite">
            <div class="icon-card card">
                <img src="{% static 'admin_portal/Img/house-building.png' %}"/>
                <h2>Check Into Field or Home</h2>
            </div>
            </a>
        </div>
        <div class=" col-6 col-md-4 col-lg-3 d-none">
            <a href="/chat">
            <div class="icon-card card">
                <img src="{% static 'admin_portal/Img/conversation.png' %}"/>
                <h2>Messages</h2>
            </div>
            </a>
        </div>
        <div class=" col-6 col-md-4 col-lg-4">
            <a href="/leave-application">
            <div class="icon-card card">
                <img src="{% static 'admin_portal/Img/calendar-interface-symbol-tool.png' %}"/>
                <h2>Leave Days</h2>
            </div>
            </a>
        </div>

    </div>
        <!--to here-->
    </div>

</div>
{% endblock content %}

templates/password_reset_done.html
{% extends 'login_base.html' %}
{%block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock %}